project:
  type: book

book:
  favicon: r4ks Logo square 512.png
  cover-image: r4ks Logo square 512.png
  site-url: https://r4ks.com
  repo-url: https://www.github.com/kjayhan/R4KS
  title: "R for Korean Studies: A Gentle Introduction to Computational Social Science"
  subtitle: "Draft Version: 0.0.1"
  author: "[Kadir Jun Ayhan, Ph.D.](https://ayhan.phd)"
  date: today
  version: 0.0.1
  google-analytics: "G-6J6HBMRCFK"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  page-footer:
    left: "© 2024 [Kadir Jun Ayhan](https://ayhan.phd) & [K-Analytics](https://k-a.phd) - [Linkedin](https://www.linkedin.com/company/k-a-phd/) - [Email](mailto:k@ayhan.phd)"
    right: "Written with [Quarto](https://quarto.org/) - Source code on [GitHub](https://github.com/kjayhan/R4KS)"
  chapters:
    - index.qmd
    - intro.qmd
    - setup.qmd
    - sources.qmd
    - basics.qmd
    - wrangling.qmd
    - visuals-tables.qmd
    - visuals-plots.qmd
    - visuals-maps.qmd
    - text.qmd
    - stats.qmd
    - quarto.qmd
    - productivity.qmd
    - api.qmd
    - kdiplo.qmd
    - bootcamp.qmd
    - references.qmd
bibliography: references.bib
format:
  html:
    theme: cerulean
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
    mainfont: Arial Unicode MS
editor: visual
freeze: true
execute:
  warning: false
  message: false