# Preface {.unnumbered}

Korean Studies is traditionally dominated by scholars of history and literature. It’s relatively rare to see R, Python, or other computational social science tools being used or taught in this field.

I believe computational social science offers huge opportunities for Korean Studies, not only for quantitative research but also for qualitative studies, including those on history and literature!

In this book, I aim to increase data literacy and convince as many Korean Studies scholars and students as possible about the relative ease of learning R with code samples, and motivational case studies about Korea.

This book is supposed to be a gentle introduction, so I do not go into the details of the R language. You can refer to the links that I provide in this book for more information. Furthermore, I also strongly encourage you to use [`Github's Copilot`](https://github.com/features/copilot) which is free for academic use, [`ChatGPT`](https://chat.openai.com/) which is not necessarily a coding bot, but still helpful especially for simple tasks, [`Stackoverflow`](https://stackoverflow.com/), and [`Google`](https://www.google.com) for help whenever you are stuck or come across an error.

I also encourage you to join our bootcamps for problem solving! You can [sign up for my newsletter to get updates on the bootcamps](https://mailchi.mp/29054dcc1b0d/dr-ayhan-newsletter).

# Current Status of the Book

-   0.Preface: Nearly Complete
-   9.Text Analysis: 50% Complete
-   14.Making Korean Data Visualization Social: Nearly Complete
-   15.Bootcamp: Nearly Complete

I will complete the Text Analysis chapter and then move on to the next chapters. Subscribe to [my newsletter](https://mailchi.mp/29054dcc1b0d/dr-ayhan-newsletter) to get updates on the book and the bootcamps.

# How to Cite This Book

This book is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 United States License. You can check the license [here](https://github.com/kjayhan/R4KS/blob/master/LICENCE).

You can freely use this book, but you must cite my work to avoid plagiarism. You can cite it in the following way: [@ayhan_2024_r4ks].

```{r, eval = F}
@book{ayhan_2024_r4ks,
  title = {R for {Korean Studies}: A Gentle Introduction to {Computational Social Science}},
  author = {Ayhan, Kadir Jun},
  year = {2024},
  month = {May},
  edition = {Draft Version 0.0.1},
  url = {https://r4ks.com}
}
```
